DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id INTEGER NOT NULL AUTO_INCREMENT,
    userId VARCHAR(32) NOT NULL,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(32) NOT NULL,
    role VARCHAR(48) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    email VARCHAR(32) NOT NULL,
    address VARCHAR(100) NOT NULL,
    createDate DATETIME NOT NULL,
    updateDate DATETIME NOT NULL,

    PRIMARY KEY (id)
);